[상추] step-1 index.html 응답
codesquad-members-2024/be-was-neon pull request #1
Opened 2024-03-11 09:41 UTC by parksangchu

## 구현 내용

- RequestHeader 정보를 출력할 수 있습니다.
  - 클라이언트가 보내는 InputStream을 BufferReader를 사용하여 읽고 로그로 출력하도록 하였습니다.
- 정적 리소스의 파일 경로를 찾을 수 있습니다.
  - 사용자가 요청한 헤더에서 url을 추출하고 url 패턴이 정적리소스를 요청하는 것이라면 static 폴더에 있는 파일을 찾아서 responseBody에 담도록 하였습니다.
- 파일에 맞는 Content-type을 매핑할 수 있습니다.
  - 응답하는 파일에 따라 다른 Content-type을 responseHeader 정보에 담야아합니다.
  - 따라서 ContentTypeMapper라는 클래스를 통해 파일 확장자에 따른 Content-type을 반환하도록 구현하였습니다.

## 고민 사항

- 상태 필드가 없는 클래스를 모두 static으로 만들어도 괜찮은가? 
  - FileManager와 같은 클래스는 유틸 기능을 가지고 있음과 동시에 필드를 가지고 있지 않습니다.
  - 따라서 인스턴스도 필요 없다고 생각했기 때문에 메서드를 모두 static 으로 구현하였습니다.
  - 하지만 static으로 구현하는 것이 안티패턴이라고 기존에 들은적이 있어서 static 으로 만드는 기준을 어떻게 잡아야할지 고민입니다.

## 기타

2024-03-11 09:43 UTC, parksangchu commented
라벨 수정 권한이 없어서 라벨은 아직 지정하지 못했습니다! ㅜㅜ

2024-03-12 00:43 UTC, honux77 commented
요구사항인 Concurrent 패키지로 수정은 구현이 안 되어 있네요. 추가로 구현해 주세요.

2024-03-12 00:43 UTC, honux77 requested changes
요구사항 확인하시고 빠진 부분 구현해 주세요.

2024-03-12 01:10 UTC, parksangchu commented
> 요구사항 확인하시고 빠진 부분 구현해 주세요.

마침 feature2에서 구현중이었어서 현재 브런치로 cherry-pick 하고 다시 push 했습니다!

2024-03-12 06:04 UTC, honux77 commented on src/main/java/utils/FileManager.java
> +    public static final String STATIC_DEFAULT_DIRECTORY_PATH = "./src/main/resources/static";
이것보다 좋은 방법은 없을까요?

2024-03-12 06:18 UTC, honux77 commented on src/main/java/webserver/WebServer.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(THREAD_POOL_SIZE);
코드의 일관성을 위해서 private 멤버로 바꿔도 좋을 것 같아요.

2024-03-12 06:18 UTC, honux77 commented on src/main/java/webserver/WebServer.java
> +    public static final int THREAD_POOL_SIZE = 200;
200도 근거가 있으면 더욱 좋겠습니다.

2024-03-12 06:18 UTC, honux77 approved these changes
수고하셨습니다!

2024-03-12 06:18 UTC, merged