[Alex] Step 3 다양한 콘텐츠 타입 지원
codesquad-members-2024/be-was-neon pull request #102
Opened 2024-03-20 13:05 UTC by horanga

## 구현 내용

-html 형식 이외의 다양한 형식의 파일을 지원하도록 기능 구현

## 고민 사항

확장에는 열려있고, 변경에 닫혀있으려면 인터페이스를 써야 하는가?
-소켓으로 들어오는 request와 response의 종류가 늘어날 것이라고 예상해서, 처음부터 이 두 가지를 인터페이스로 설정하고 구체적인 클래스를 하나씩 만들었습니다. (post 페이지를 불러오는 것, 회원가입창을 불러오는 것, 회원가입을 하는 것 등등)

이 클래스들이 단순히 파일의 path정도만을 반환하는 역할을 해서 이렇게 확장을 해도 괜찮을지?를 고민했습니다.
역시 이번에 다양한 파일의 형식을 지원하다보니 클래스 개수가 생각보다 많이 늘어나서 고민이 커지네요.
(혹시 리뷰하실 때 놀라실수도... path 패키지에 있는 클래스들은 단순히 path 문자열을 반환하는 역할만 합니다.)

다른 분들처럼 map을 쓰거나 enum을 활용해도 괜찮을 거 같지만서도, 그렇게 하면 기능을 확장할 때 기존 코드를 수정해야해서 인터페이스를 활용했습니다.

확실히 새로운 종류의 request나 response를 추가할 때는 기존 코드를 건드리지 않아도 된다는 점이 체감이 됐습니다.

다만, 여기서 다시 Factory라는 추가적인 단계를 넣어서 설계를 너무 복잡하게 꼬아버린 느낌이 없잖아 있습니다... css나 html svg모두 파일 형식별로 어떤 파일을 써야할지 분기점을 나눠야 하는데, 이것 역시 로직이 조금 복잡해질 수 있어 팩토리를 이용했습니다. (설계가 복잡해졌지만, 팩토리와 enum을 활용하니 분기점을 나누는 늪에서 벗어날 수 있었다는 점이 긍정적이라고 생각했습니다...)

이 문제 역시 map이나 enum을 썼으면 쉽게 해결될 수 있을 거 같은데...그렇다면 객체지향적으로 클래스를 만들 필요가 있나?.. 하는 의문이 들고 모든 걸 다 map이나 enum에 넣고 해결해버리면 되는 거 아닌가... 하는 의구심이 들어서 전반적인 설계는 아쉬움이 여전히 많지만, 제 생각에는 클래스를 활용하는 것이 좀더 객체지향적이지 않을까 싶어서 기존 설계를 활용해서 기능을 구현하고 pr을 보냅니다.

## 기타

2024-03-21 09:45 UTC, honux77 commented on src/main/java/http/request/factory/IcoPathFactory.java
이 클래스가 왜 필요한지 전혀 모르겠어요.

2024-03-21 09:46 UTC, honux77 requested changes
정적 파일들의 경로를 만들어내는 팩토리들은 모두 필요없어 보입니다.
다 제거하고 static 경로의 파일들을 하나의 클래스와 메소드에서 다 읽고 처리할 수 있게 다시 구현해 보세요.

2024-03-21 14:48 UTC, horanga commented on src/main/java/http/request/factory/IcoPathFactory.java
내용 변경했습니다!

2024-03-22 05:23 UTC, honux77 commented on src/main/java/http/request/factory/PathFactories.java
@horanga  이 클래스도 필요 없어요. 이거 없이 static 폴더를 하위 폴더 구조를 참고해서 바로 읽을 수 있도록 다시 고민해 보세요. 
일단 진도가 늦었으니 머지할테니 나중에 꼭 고쳐보세요!

2024-03-22 05:23 UTC, honux77 approved these changes
여튼 긴 시간 고생 많으셨습니다. 화이팅!

2024-03-22 05:23 UTC, merged