[제이든] 웹 서버 5단계 - 쿠키를 이용한 로그인
codesquad-members-2024/be-was-neon pull request #117
Opened 2024-03-22 04:18 UTC by hiidy

## 구현 내용

- 쿠키와 세션 클래스를 추가해서 세션 쿠키를 처리할 수 있도록 함.
- 서버에 쿠키를 따로 저장하지 않고 session manager라는 곳에 sessionID와 관련된 정보를 저장하도록 함.
- DB에 user 객체를 저장하는 기능을 추가. DB에 저장을 할 때 동시성 문제를 해결하기 위해서 concurrentHashmap을 사용했습니다.

## 질문 및 고민
- DB에 user 객체를 저장할 때  동시성 문제를 해결하기 위해서(동시에 회원가입 or  로그인) concurrentHashmap을 사용했습니다. 그런데 과연 concurrentHashmap을 사용하는 것이 최선의 방법인지 다른 방법이 더 있는지 궁금증이 생깁니다...
- 저의 was는 사용자가 처음 로그인하면 서버측에서는 쿠키 객체를 만들고 header에 이 쿠키 객체를 바탕으로 response를 합니다.(동시에 session manager에 session id와 유저id를 같이 추가). 제가 더 공부해본 바로는 보안을 강화하기 위해서 기존에 쿠키만 사용하던 것에 세션을 더해서 쿠키를 전달하는 것인데 완벽하게 구현하려면 사용자가 브라우저를 닫으면 세션이 닫혀지게 해야된다고 합니다. 이런 식으로 세션을 구현하는것이 맞는 방법인지 궁금합니다.

2024-03-26 06:33 UTC, honux77 commented on src/main/java/webserver/Cookie.java
> +public class Cookie {
쿠키는 우리가 설정하지 않더라도 다양한 값들이 들어올 수 있는데 지금 코드는 sid와 path만 설정가능하군요.
set(key, value) 같은 일반적인 메소드도 있으면 좋을 것 같아요.

2024-03-26 06:39 UTC, honux77 requested changes
지금 Session과 쿠키의 관계가 좀 이상하게 구현이 된 거 같아요.
SessionDB의 보통 k: sessionID V: Session 인데 Session에 sid가 있을 필요는 없습니다.
지금 상황이라면 k: sseion, V: User 객체 또는 User의 닉네임 정도만 저장해도 되구요. 

이 부분에 대해 다시 공부해서 수정해 주시면 좋을 것 같아요.

2024-03-26 08:20 UTC, hiidy commented
> 지금 Session과 쿠키의 관계가 좀 이상하게 구현이 된 거 같아요. SessionDB는 보통 k: sessionID V: Session 인데 Session에 sid가 있을 필요는 없습니다. 지금 상황이라면 k: sseionID, V: User 객체 또는 User의 닉네임 정도만 저장해도 되구요.
> 
> 이 부분에 대해 다시 공부해서 수정해 주시면 좋을 것 같아요.

session 객체랑 session store코드를 수정했습니다. 세션에 user 특성이 아닌 다른 특성이 들어갈 수 있다고 생각해서 session 객체에 세션정보를 담고 session store에는 다른 user들의 세션들이 저장될 수 있도록 코드를 수정했습니다.

2024-03-27 02:25 UTC, honux77 commented on src/main/java/webserver/session/Cookie.java
지금 쿠키가 세션 패키지에 있는데 쿠키와 세션은 사실 아무 관계가 없어요 ㅜㅜ. 
쿠키는 Http Request 패키지에 있어야 할 것 같습니다.

2024-03-27 02:27 UTC, honux77 commented on src/main/java/webserver/session/Cookie.java
> +    public Cookie setSessionID(String sessionID) {
지금 보니 쿠키라고 하는 객체가 명시적으로 세션 ID를 세팅하는 것도 이상합니다.
Cookie는 set(k, v), get(k, v) 정도를 가지는 게 적당해 보여요.

쿠키는 세션을 구현하기 위한 게 아니라 무상태인 HTTP를 보완하기 위한 스펙의 일부라는 걸 인지하면 좋겠습니다.

2024-03-27 02:28 UTC, honux77 commented on src/main/java/webserver/session/Session.java
👍

2024-03-27 02:28 UTC, honux77 commented on src/main/java/webserver/session/SessionStore.java
👍

2024-03-27 02:28 UTC, hiidy commented on src/main/java/webserver/session/Cookie.java
넵넵 쿠키 location도 수정하겠습니다. 위에서 제가 수정한것처럼 여러 세션 특성값을 저장하기 위해서 위해서 session 객체를 따로 만들어서 관리하는 방식은 괜찮은건가요??

2024-03-27 02:28 UTC, honux77 approved these changes
수정 내용 확인했습니다. 수고하셨어요~ 쿠키에 대한 코멘트만 한 번 더 확인해 주세요~\?
👏

2024-03-27 02:28 UTC, merged