[그로밋] step-5 로그인 기능 구현
codesquad-members-2024/be-was-neon pull request #118
Opened 2024-03-22 05:58 UTC by jonghyeok-97

## 구현 내용
* `request` 클래스만 사용하도록 `request` 패지키의 `request` 클래스를 제외한 클래스들의 접근 제어자를 default 로 수정
* 다양한 `response` 를 만들 수 있도록 `builder` 패턴을 사용해서 `response` 객체를 만듬.
* `handler`패키지에서 로그인, 회원가입,  파일을 읽는 기능을 구현.
## 고민 사항
* `Request` 클래스에 `inner class` 를 만들고, 이 곳에서 리퀘스트메시지를 파싱 및 분석함.
  * 하지만, `inner class` 에 접근하지 못하도록 접근 제어자를 private 으로 만드니, inner class 의 Test가 어려워짐
  * 전체 리퀘스트 메시지가 올바르게 라인, 헤더, 바디 로 파싱되는지 `Test` 로 알아야 할까? 란 생각을 했을 때, 이 것을 테스트 하는 것이 아닌 각각의 라인 객체, 헤더 객체, 바디 객체가 잘 생성되는지 확인하는 것이 더 낫겠다라는 생각을 했는데, 괜찮은 생각인지 궁금합니다.
## 기타
* 중복 제거 및 `handler`의 로직을 정리하는 등 리팩토링 필요성이 남아있음.
* `domain`인 `user` 클래스와 `request` 를 분리해야 하는 시도가 필요함.
* `request`에서 `resources` 에 있는 `File` 을 찾아서 보내주고 있는데, 이를 `handler` 의 로직으로 옮김으로써 패키지 의존성을 낮추고자 함.
* 로그아웃 기능을 구현하지 않음.
* WAS 를 만드는 것이 아닌 MyWas 를 만듬 -> 그 이유로 HTTP 및 WAS의 동작에 대한 이해가 부족하다고 느낌 -> 주말에 공부할 예정.

2024-03-26 06:42 UTC, honux77 commented
위 질문에 덧붙여서 FileHandler 에서 URI에 해당하는 파일이 존재하는지 확인하는 isExistFile 이란 기능에서 파일을 생성해서 존재하는지만 확인하고 버리게 되는데, 만약 이 파일이 커서 생성하는데 많은 비용이 들면 제가 만든 로직은 효용이 떨어진다고 생각합니다. --> 이 질문은 질문의 내용이 정확한지 다시 한 번 생각해 보세요 ^^

2024-03-26 06:43 UTC, honux77 commented on src/main/java/model/Session.java
> +    public static String createSessionID() {
이건 뭘까요?

2024-03-26 06:47 UTC, honux77 commented on src/main/java/model/Session.java
> +    public static String createSessionID() {
지금 코드에서는 항상 세션 ID가 일정하기 때문에  두 번째 사용자가 로그인하면 안 될 것 같아요.

2024-03-26 06:48 UTC, honux77 requested changes
세션 ID가 항상 동일하게 발급되고 있는데 해당 부분은 수정해야 할 것 같아요.
확인해 주세요.

2024-03-27 02:32 UTC, honux77 commented on src/main/java/db/SessionDB.java
> +    public static void add(Cookie cookie, User user) {
세션에 쿠키를 넣는 게 아니라 쿠키에서 읽어온 sid를 키값으로 넣는 게 바람직합니다.

2024-03-27 02:33 UTC, honux77 commented on src/main/java/model/Cookie.java
> +public class Cookie {
지금 세션 아이디와 쿠키의 개념을 혼동해서 사용하고 있어요. 다시 확인하고 코드 수정해 주세요.

2024-03-27 02:34 UTC, honux77 requested changes
그로밋 계속 수정 요청을 해서 좀 미안한데 쿠키와 세션의 개념에 대해 다시 한 번 공부하고 코드를 고쳐주면 좋겠어요. 

쿠키는 HTTP 요청에 기본적으로 들어가 있는 스펙의 일부이고
세션은 이와 직접적인 관계가 없다는 점도 기억해 주세요.

2024-03-27 02:53 UTC, jonghyeok-97 commented
> 그로밋 계속 수정 요청을 해서 좀 미안한데 쿠키와 세션의 개념에 대해 다시 한 번 공부하고 코드를 고쳐주면 좋겠어요.
> 
> 쿠키는 HTTP 요청에 기본적으로 들어가 있는 스펙의 일부이고 세션은 이와 직접적인 관계가 없다는 점도 기억해 주세요.

아닙니다!! 잘못 이해한 지식을 바로 잡는 것이 더 좋다고 생각합니다!
오히려 확실하게 세션과 쿠키의 관계를 이해하고 PR을 보냈어야 했는데, 제가 더 죄송합니다.🙇‍♂️
PR의 중요성을 다시 한 번 생각하며 앞으로 있을 미션에 임해보도록 하겠습니다

2024-03-27 11:06 UTC, jonghyeok-97 commented
> 위 질문에 덧붙여서 FileHandler 에서 URI에 해당하는 파일이 존재하는지 확인하는 isExistFile 이란 기능에서 파일을 생성해서 존재하는지만 확인하고 버리게 되는데, 만약 이 파일이 커서 생성하는데 많은 비용이 들면 제가 만든 로직은 효용이 떨어진다고 생각합니다. --> 이 질문은 질문의 내용이 정확한지 다시 한 번 생각해 보세요 ^^

`new File(filePath)` 를 하면 파일이 생성될것이라는 착각 속에서 질문을 드린 것 같습니다!
또한, 파일을 다룰 때, new File 을 하는 과정에서의 비용을 고려할 것이 아닌 `File` 클래스의 `isExist()` 란 메서드를 호출할 때의 비용을 고려해야 함을 알게되었습니다. 파일을 찾기 위해 `isExist` 를 호출하면 Java는 아무일도 하지 않고, OS의 파일시스템이 찾게 됨을 알게 되었습니다. 결국은 개인 프로젝트에서 `isExist`의 비용은 고려하지 않아도 될 것입니다.
참고 자료 : https://stackoverflow.com/questions/6321180/how-expensive-is-file-exists-in-java

2024-03-28 02:44 UTC, jonghyeok-97 commented
## 구현 내용
* 클래스의 생성자, 메서드의 접근 제어자를 `default` 혹은 `protected` 로 수정해서 코드스타그램의 서버를 만드는데 필요 없는 클래스 및 메서드의 접근을 막음.
* 다양한 `response` 를 만들 수 있도록 `builder` 패턴을 사용해서 `response` 객체를 만듬.
* `http` 와 코드스타그램을 분리하여 `http` 패키지에 클래스들이 코드스타그램의 요구사항을 처리했던 기존 기능들을 제거함
## 고민 사항
* `Request` 클래스에 `inner class` 를 만들고, 이 곳에서 리퀘스트메시지를 파싱 및 분석함.
  * 하지만, `inner class` 에 접근하지 못하도록 접근 제어자를 private 으로 만드니, inner class 의 Test가 어려워졌습니다.
  * 전체 리퀘스트 메시지가 올바르게 라인, 헤더, 바디 로 파싱되는지 `Test` 로 알아야 할까? 란 생각을 했을 때, 이 것을 테스트 하는 것이 아닌 각각의 라인 객체, 헤더 객체, 바디 객체가 잘 생성되는지 확인하는 것이 더 낫겠다라는 생각을 했는데, 괜찮은 생각인지 궁금합니다. 
## 기타
* 로그인, 가입 `Handler`에서 `User` 를 만들어서 `DB`에 넣고 있는데 이 부분을 분리 시켜보겠습니다.
* feature5 를 PR 보냈을 때, 충돌이 일어나서 Auto-merge 가 되지 않는 상황을 local 환경에서 해결.
  1. 로컬 Gromit 브랜치에서 새 브랜치(feature5-conflict) 하나 파고, 이 곳에 upstream 그로밋 브랜치를 fetch 와 rebase함.
  2. 새 브랜치에 merge feature5
  3. 직접 충돌난 코드 부분 수정.
  4. switch feature5
  5. feature5 merge feature5-conflict 
  6. git push origin feature5
* `Cookie`  클래스
  * 클라이언트가 원하는 쿠키의 속성을 `key` 와 `value` 로 받음
  * 내부적으로 쿠키의 속성들을 합쳐서 `Response`에게 보내줌
* `SessionManager`
  * `SID`와 `User` 를 매핑해서 갖고 있음
  * `SID`를 생성, 추가, 제거함

2024-03-28 06:19 UTC, honux77 commented on src/main/java/http/SessionManager.java
👍

2024-03-28 06:23 UTC, honux77 approved these changes
👍수고하셨습니다. 🥇

2024-03-28 06:23 UTC, merged