[Zoonmy] step-5 쿠키를 이용한 로그인
codesquad-members-2024/be-was-neon pull request #130
Opened 2024-03-26 10:42 UTC by pjm2571

## 구현 내용
- RequestReader를 따로 두어, InputStream을 읽어 HttpRequest객체를 리턴하도록 구현
- HttpRequest 객체에 startLine, header, body 타입 객체를 따로 만들어 일급 컬렉션으로 동작하도록 구현
- UrlHandler에 대해 팩토리 패턴을 활용하여 각각의 url에 따른 handler가 동작할 수 있도록 구현
## 고민 사항
- Config 설정 파일을 사용하게 되는데, config가 여러곳에서 사용되다 보니 config 객체를 계속해서 넘겨주어야 하는 문제가 발생. 이를 static 으로 생성하여 동적으로 값을 가져올 수 있도록 개선해보자

## 기타

2024-03-27 03:11 UTC, honux77 commented on src/main/java/webserver/constants/Constants.java
> +public class Constants {
상수를 모아두는 방식도 예전에는 많이 사용했는데 저는 이렇게 하면 변경사유가 많아져서 수정이 빈번하게 일어날 가능성이 높다고 생각해요. 각 상수는 필요한 곳에 두는 게 더 낫지 않을까요?

2024-03-27 03:18 UTC, honux77 commented on src/main/java/webserver/handler/url/LoginHandler.java
> +package webserver.handler.url;
패키지 이름이 다소 모호해요. 왜 마지막이 url 인지 잘 모르겠어요.

2024-03-27 03:54 UTC, honux77 commented on src/main/java/webserver/handler/url/RegistrationHandler.java
> +    private HttpResponse handleGet(HttpRequest httpRequest, Config config) {
정적인 URL이지만 따로 등록을 위해 처리를 했군요. 회원 가입 폼은 그냥 register/index.html 로 정적 파일을 읽어 응답하도록 처리해도 될 거 같은데 별도로 처리를 한 이유가 있는지 궁금합니다.

2024-03-27 04:05 UTC, honux77 commented on src/main/java/webserver/utils/HttpRequestUtils.java
> +public class HttpRequestUtils {
클래스의 이름과 하는 일이 맞지 않는 느낌입니다. RequestUtil인데 왜 Response를 생성하는 걸까요?

2024-03-27 04:07 UTC, honux77 commented on src/main/java/webserver/utils/HttpRequestUtils.java
> +    public static String generateRedirectResponseHeader(String redirectTarget, String sid) {
이 메소드에 쿠키를 설정하는 부분이 감춰져 있어서 해당 부분을 코드만으로 찾아내기 어려웠어요.
쿠키를 설정하는 부분은 별도의 메소드로 명시적으로 빼는 게 좋겠습니다.

2024-03-27 04:09 UTC, honux77 requested changes
쿠키를 처리하는 코드를 별도로 분리해서 메소드의 이름만으로도 동작을 이해할 수 있도록 변경해 주시면 좋겠습니다. 

그리고 정적 파일을 처리하는 코드도 다소 중복이 있어 보이는데 개선 가능하면 개선하면 좋겠어요.

2024-03-27 09:43 UTC, pjm2571 commented on src/main/java/webserver/constants/Constants.java
> +public class Constants {
저는 오히려 상수를 바꾸게 된다면, Constants 클래스에서만 수정하면 된다고 생각하여서 이렇게 구현하였는데, 구현을 하다 보니 상수가 사용되는 곳이 정해져 있어서.. 따로 필요한 곳에 두는 곳이 더욱 좋을 것 같다고 생각했습니다!
Step-6을 진행하면서, 리팩토링한 부분이 있었는데 step-5 merge 후에 rebase하여 반영하도록 하겠습니다 !

2024-03-27 09:43 UTC, pjm2571 commented on src/main/java/webserver/handler/url/LoginHandler.java
> +package webserver.handler.url;
패키지 이름 수정하겠습니다!

2024-03-27 09:46 UTC, pjm2571 commented on src/main/java/webserver/handler/url/RegistrationHandler.java
> +    private HttpResponse handleGet(HttpRequest httpRequest, Config config) {
확장 가능성을 염두에 두고 구현을 한 것이긴 한데.. 구현을 함에 있어서 /registration으로의 get 요청은 정적인 url만 처리해주면 되기 때문에 프로그램의 복잡도만 올린 것 같다고 생각되긴 하네요.. 

step-6을 구현하면서 user/login_failed와 user/list를 구분하기 위해 위와 같은 방식을 생각하게 되었는데 오늘 OOP 강의를 듣고 조금 더 개선해보아야겠습니다.

2024-03-27 09:46 UTC, pjm2571 commented on src/main/java/webserver/utils/HttpRequestUtils.java
> +public class HttpRequestUtils {
HttpRequestUtils와 HttpResponseUtils를 분리하여 구현하도록 수정하였습니다.

하지만, utils에서 response를 만들어주는 것이 맞는 지 조금 어색한 기분이 들어서 리팩토링을 조금 더 해볼 생각입니다.

2024-03-27 09:47 UTC, pjm2571 commented on src/main/java/webserver/utils/HttpRequestUtils.java
> +    public static String generateRedirectResponseHeader(String redirectTarget, String sid) {
네. setCookieHeader 메소드를 따로 선언하여 header에 대해 cookie를 설정하는 메소드를 분리할 수 있도록 리팩토링하였습니다.

2024-03-27 09:52 UTC, pjm2571 commented
> 쿠키를 처리하는 코드를 별도로 분리해서 메소드의 이름만으로도 동작을 이해할 수 있도록 변경해 주시면 좋겠습니다.
> 
> 그리고 정적 파일을 처리하는 코드도 다소 중복이 있어 보이는데 개선 가능하면 개선하면 좋겠어요.

이전 프로젝트의 honux 가 해주신 리뷰를 보고 url을 기준으로 동작하는 프로그램을 구현하고 싶었습니다. 그러다보니, urlHandler로 url을 처리해주게 되었습니다.
단순히 url 요쳥일 경우에는 StaticFileHandler를 통해 정적파일을 생성하도록 구현하였는데, 이번 프로그램에서의 GET 요청은 모두 정적 파일 load이기때문에 수정할 필요가 있어 보인다고 생각하게 되었습니다.

url -> GET or POST 처리 의 방식으로 처리하다보니, 정적 파일을 처리하는 코드가 다소 중복된 것 같은 느낌이 들었습니다.

2024-03-28 06:26 UTC, honux77 approved these changes
수고하셨습니다. 기능 구현과 리팩토링의 밸런스를 적절하게 맞추면서 진행해 보세요!

2024-03-28 06:26 UTC, merged