[kalia] Step04 POST로 회원가입
codesquad-members-2024/be-was-neon pull request #136
Opened 2024-03-28 06:26 UTC by kalia013

## 구현 내용
### 1. 리다이렉트 구현
### 2. 회원가입 GET에서 POST로 변경
### 3. 구조 개선
## 고민 사항
### 1. 리다이렉트 구현
step04를 하면서 가장 고민이 됬던 건 아무래도 리다이렉트 부분이였습니다.
기존의 RouteManager부분과 Redirect 부분이 중복되고, 하드 코딩적인 부분이 너무 강해서
이걸 어떻게 처리하지 고민을 한 결과 기존의 구조를 바꿨습니다.
기존의 정적 파일 경로를 다루는 RouteManager 클래스는 파일의 컨텐트 타입만 다루게 만들었습니다.
그러고 RedirectProcessor 인터페이스 및 구현 클래스들을 각각 만들어서 리다이렉트를 해결해줬습니다.

### 2. 회원가입 GET에서 POST로 변경
POST 요청의 바디에서 사용자 정보를 파싱해서 USER 객체를 반환하는 형식으로 구현했습니다.

### 3. 구조 개선
책임을 분할 했습니다.
HttpRequest는 값만 가지게 하고
HttpRequestReader에서 받은 HTTP 요청을 전체 읽어서 문자열로 반환을 담당하게 했습니다.
HttpResponseWriter는 해당 요청의 응답만을 다루게 했습니다.
리다이렉트나 Utils 관련도 역할을 최대한 나눠봤습니다.

## 기타
생각보다 초반에 방향을 잘못 잡아서 다시 돌아가는데 오래 걸렸지만
그래도 유의미한 리팩토링이였던 것 같습니다.

2024-03-29 04:43 UTC, honux77 commented on src/test/java/HttpRequestParserTest.java
> +    @Test
테스트에는 `displayName` 꼭 사용해 주세요!

2024-03-29 04:44 UTC, honux77 commented on src/main/java/Redirect/CreateProcessor.java
> +package Redirect;
패키지 안의 클래스가 전부 리다이렉트용이 아닌데요. 더 자신을 표현할 수 있는 이름으로 수정해 주세요.

2024-03-29 04:45 UTC, honux77 commented on src/main/java/Redirect/CreateProcessor.java
> +public class CreateProcessor implements RequestProcessor {
이름도 이상하고 내용도 너무 없어요.  이렇게 짧은 클래스는 어딘가 다른 누구에게 포함되는 게 더 좋을 가능성이 높습니다.

2024-03-29 04:46 UTC, honux77 commented on src/main/java/Redirect/RedirectSelector.java
> +public class RedirectSelector {
redirect는 중요한 프로세스가 아니라 회원가입, 로그인의 결과로 나오는 부수적인 행동일 뿐인데 이렇게 별도로 클래스로 되어 있는게 좀 어색해요.

2024-03-29 04:49 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +    private void closeConnection() {
try with 문법으로 쓰는 게 더 좋아 보여요.

2024-03-29 04:50 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +            HttpRequestReader requestReader = new HttpRequestReader(connection);
리더에 connection을 주는 것보다 종래대로 in 만 주는 게 더 좋아 보입니다.

2024-03-29 04:51 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +            String httpRequest = requestReader.readRequest();
httpRequest는 String이 아니라 객체로 수정해 주세요.

2024-03-29 04:51 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +            HttpRequest request = new HttpRequest(httpRequest);
```suggestion
            HttpRequest request = new HttpRequest(requestReader.readRequest());
```

2024-03-29 04:52 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +            RequestProcessor processor = RedirectSelector.getProcessor(request.getPath());
```suggestion
            RequestProcessor processor = RedirectSelector.select(request.getPath());
```

2024-03-29 04:53 UTC, honux77 commented on src/main/java/webserver/RequestHandler.java
> +            if (processor != null) {
Optional을 적용해 보시면 좋을 것 같습니다.

2024-03-29 04:55 UTC, honux77 commented on src/main/java/Redirect/RedirectSelector.java
> +        routeMap.put("/registration", new RegistProcessor());
왜 create 도 있고 registation도 있는지 다소 의아하군요..

2024-03-29 05:07 UTC, honux77 requested changes
POST 로 회원가입하려면
1) method = POST 인지 확인  
2) URL = 회원가입 URL 일치 여부 확인 
3) 데이터베이스에 사용자 정보 추가 
4) 리다이렉트 

인데 이 흐름이 잘 보이지 않아요. 
깔끔하게 흐름이 보이도록 구조를 개선하면 좋겠어요. 
그리고 Redirect 패키지의 클래스들은 이름 / 행동이 다소 모호하니 구조를 전반적으로 개선하면 좋겠습니다.

2024-03-29 05:45 UTC, kalia013 commented on src/main/java/webserver/RequestHandler.java
> +            if (processor != null) {
null 사용을 피하겠습니다.

2024-03-29 06:44 UTC, kalia013 commented on src/main/java/webserver/RequestHandler.java
> +            HttpRequestReader requestReader = new HttpRequestReader(connection);
connection 그자체를 주지 않고, 각각 Reader와 Writer에 in과 out을 각각 보내겠습니다!

2024-03-29 06:45 UTC, kalia013 commented on src/main/java/Redirect/RedirectSelector.java
> +        routeMap.put("/registration", new RegistProcessor());
/create 요청이 왔을 떄, /registration 요청 이제 이걸 다르게 생각해서 생긴 문제인것 같습니다 ㅠㅠ

2024-03-29 06:46 UTC, kalia013 commented on src/main/java/Redirect/RedirectSelector.java
> +public class RedirectSelector {
지금 리다이렉트를 쓰는건 사실상 회원가입 /create 밖에 없는데, 제가 요청과 리다이렉트를 같은 개념으로 생각해서 일어난 문제 같습니다.

2024-03-29 06:46 UTC, kalia013 commented on src/main/java/Redirect/CreateProcessor.java
> +public class CreateProcessor implements RequestProcessor {
지금 일단 /registration과 /create 관련 프로세스를 한번 합쳐볼 생각입니다.

2024-03-29 06:48 UTC, kalia013 commented on src/main/java/Redirect/CreateProcessor.java
> +package Redirect;
지금 요청과 리다이렉트를 같은 개념으로 생각한게 문제가 생긴것 같은데, 일단 GET 요청과 POST요청을 분리해서 다시 구조를 개선해야 할 것 같습니다.

2024-04-02 01:38 UTC, honux77 approved these changes
@kalia013 변한 게 없어 보이지만 일단 시간이 오래 지나서 머지 할게요.
속도가 좀 늦은 편이니 일단 구조보다는 기능에 초점을 맞춰서 빨리 해 보세요.

2024-04-02 01:38 UTC, merged

2024-04-03 06:14 UTC, kalia013 commented
앗....아직 하고 있었습니다..ㅠㅠㅠ 개선하면서 진행하겠습니다...!
commit push를 안 하고 있었네요....