[Juju] step-4 POST로 회원 가입
codesquad-members-2024/be-was-neon pull request #91
Opened 2024-03-19 13:21 UTC by ohjuyoungg

## 구현 내용
-  회원가입 시 GET 요청에서 POST 요청으로 변경했습니다.
- 회원가입 후 /index.html 페이지로 이동하게 구현했습니다.
   - HTTP 응답 헤더의 302를 사용했습니다.
   
## 고민 사항
- 리팩토링 하는 과정에서 각각의 기능 역할 별로 얼마나 어떤 기준으로 객체를 나눠야 잘 구현한 코드인지 아직 감이 안오는 것 같습니다.
- 테스트 코드 내에서 SoftAssertion 활용 

## 기타
- step3 리뷰 반영 부분

- [x] 메소드명 변경 
![image](https://github.com/codesquad-members-2024/be-was-neon/assets/71004322/cab66ead-21ec-4eac-a6a3-346e6c165bec)

- [x] byte[] body -> HttpResponse 객체 역할로 리팩토링
![image](https://github.com/codesquad-members-2024/be-was-neon/assets/71004322/1a4b25bd-ce4a-4cf4-8fb1-b77875511589)

- [x] 테스트 코드 내에 @DisplayName 어노테이션 활용
![image](https://github.com/codesquad-members-2024/be-was-neon/assets/71004322/176efd14-fd7c-4c9f-9cc8-14cb497e41d5)

2024-03-20 09:11 UTC, honux77 commented on src/main/java/webserver/MainHandler.java
> +            httpRequest.registrationParamValue(out, parameters); // parameters 전달
```suggestion
            httpRequest.registerParamValues(out, parameters); // parameters 전달
```

2024-03-20 09:12 UTC, honux77 commented on src/main/java/webserver/MainHandler.java
> +            File file = new File("src/main/resources/static" + url);
src/main/resources/static 상수로 분리해 주세요.

2024-03-20 09:12 UTC, honux77 commented on src/main/java/webserver/MainHandler.java
> +                byte[] body = httpResponse.readFileContents(file);
파일을 읽는 건 httpResponse 의 책임이 아닌 것 같아요.

2024-03-20 09:13 UTC, honux77 commented on src/main/java/webserver/MainHandler.java
>                  String type = contentType.getContentType(url);
Static 메소드로 하는 편이 낫지 않을까요?

2024-03-20 09:17 UTC, honux77 commented on src/main/java/webserver/httpMessage/HttpRequest.java
> +    public void registrationParamValue(OutputStream out, Map<String, String> params) throws IOException {
모든 HTTP 요청에 대해 이 메소드를 실행하게 되는데 
1) 지정된 URL에 대해서만 실행하게 하고 
2) 이름과 달리 사용자 가입을 여기서 하고 있지만 예측할 수가 없습니다.

그래서 

1) 이름 잘 짓기
2) 지정된 URL과 하는 일이 드러나도록 

개선해 주면 좋겠어요.

2024-03-20 09:20 UTC, honux77 commented on src/main/java/webserver/httpMessage/HttpRequest.java
> +        if (isCreateRequest()) { // isCreateRequest 메서드를 호출하여 null 체크
어딘가에서 POST 인지 확인해야 하는데 그 부분도 없습니다. 요청이 GET 일 경우 처리하지 않도록 고쳐야 할 것 같아요.

2024-03-20 09:21 UTC, honux77 requested changes
명시적으로 HTTP method 를 확인하고 처리하는 부분이 보이도록 코드 구조를 개선해야 할 것 같습니다. 화이팅! ⌨️ !

2024-03-20 18:11 UTC, ohjuyoungg commented
@honux77 호눅스께서 주신 리뷰 반영하였습니다.  :)

2024-03-20 18:12 UTC, ohjuyoungg commented on src/main/java/webserver/httpMessage/HttpRequest.java
> +    public void registrationParamValue(OutputStream out, Map<String, String> params) throws IOException {
상세하게 리뷰해주셔서 대단히 감사합니다!

2024-03-21 03:15 UTC, honux77 commented on src/main/java/model/HttpMethod.java
이런 코드가 멤버들 사이에서 자주 보이는데요.  map으로 만들어보면 어떨까 싶은 생각이 듭니다.

2024-03-21 03:15 UTC, honux77 commented on src/main/java/utils/FileSerializer.java
> +public class FileSerializer {
```suggestion
public class FileUtil {
```

2024-03-21 03:20 UTC, honux77 commented on src/main/java/utils/FileSerializer.java
> +    public static byte[] toByteArray(File file) throws IOException {
그냥 BufferedInputStream으로 한 번에 읽는 게 좋겠어요.

2024-03-21 03:21 UTC, honux77 commented on src/main/java/utils/FileSerializer.java
> +    public static byte[] toByteArray(File file) throws IOException {
금요일에 이거 다시 저에게 언급해 달라고 말해 주세요~ Plz~

2024-03-21 03:21 UTC, honux77 commented on src/main/java/utils/HttpRequestUtils.java
> +    public static HttpRequest parse(BufferedReader br) throws IOException {
메소드가 너무 긴 느낌? 분리가 필요해 보입니다.

2024-03-21 03:22 UTC, honux77 commented on src/main/java/utils/HttpRequestUtils.java
> +    public static HttpMethod getMethod(String startLine) {
요건 HttpRequest 가 가지고 있어야 할 거 같아요.

2024-03-21 03:23 UTC, honux77 commented on src/main/java/webserver/MainHandler.java
> +    private void handlerMapping(
로직은 맞는데 if else depth가 너무 깊네요. 나중에 개선해 보세요.

2024-03-21 03:23 UTC, honux77 approved these changes
👍 수고하셨습니다.

2024-03-21 03:23 UTC, merged

2024-03-21 04:57 UTC, ohjuyoungg commented on src/main/java/model/HttpMethod.java
앗 map으로 한번 만들어보겠습니다 !!

2024-03-21 04:58 UTC, ohjuyoungg commented on src/main/java/utils/FileSerializer.java
> +    public static byte[] toByteArray(File file) throws IOException {
넵 !!! 마스터 피드백 시간에 말씀드리겠습니다:)

2024-03-21 04:59 UTC, ohjuyoungg commented on src/main/java/utils/HttpRequestUtils.java
> +    public static HttpRequest parse(BufferedReader br) throws IOException {
넵넵!! 분리하겠습니다!